version: "3"
services:
    node-app:
        build:
            context: .
            args: 
                NODE_ENV: production
        environment: 
            - NODE_ENV=production
            - SESSION_SECRET=${SESSION_SECRET}
        command: node app.js
