version: "3.8"
services: 
    node-app:
        build: .
        ports: 
            - 3001:3001
        environment: 
            DB_URL: mongodb://mongo/edu
        depends_on: 
            - mongo

    mongo:
        image: mongo
        ports: 
          - 27017:27017
        volumes: 
          - edu:/data/db

volumes: 
    edu: